use strerror_r wrapper only for glibc
Compiling with clang/musl from FEX fails with:

```
FEX/External/jemalloc_glibc/src/malloc_io.c:100:8: error: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
  100 |         char *b = strerror_r(err, buf, buflen);
      |               ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Add check for `__GLIBC__` to the wrapper code to only use it with glibc,
which provides a non-standard `strerror_r()` when `_GNU_SOURCE` is defined

fixes: FEX-Emu/FEX#5106
Signed-off-by: Pepper Gray <hello@peppergray.xyz>